import type { MobileMenuCategory } from "@/components/layout/shared/MobileMegaMenuSection";

/** Shared Marketing mega-menu — used by the homepage Marketing tab and the marketing site Services dropdown. */
export const MARKETING_MENU_CATEGORIES: MobileMenuCategory[] = [
  {
    label: "Marketing & Consulting",
    subtitle: "Planning & positioning",
    avatar: "/avatar/1.avif",
    icon: "chart",
    tint: "#FFF6E6",
    iconColor: "#FDAB3D",
    items: [
      { label: "Go-to-Market Strategy", icon: "chart", href: "#" },
      { label: "ICP & Buyer Persona Definition", icon: "personPlus", href: "#" },
      { label: "Marketing Audits", icon: "clipboardCheck", href: "#" },
      { label: "Competitive Positioning", icon: "tag", href: "#" },
    ],
  },
  {
    label: "Demand Generation",
    subtitle: "Leads & pipeline",
    avatar: "/avatar/2.avif",
    icon: "funnel",
    tint: "#F3EEFF",
    iconColor: "#6161FF",
    items: [
      { label: "Account-Based Marketing", icon: "funnel", href: "#" },
      { label: "LinkedIn Lead Generation", icon: "link", href: "#" },
      { label: "Outbound & Cold Outreach", icon: "headset", href: "#" },
      { label: "Revenue Attribution & Pipeline Reporting", icon: "chart", href: "#" },
    ],
  },
  {
    label: "Search & AI Visibility",
    subtitle: "Search & discovery",
    avatar: "/avatar/3.avif",
    icon: "search",
    tint: "#E8F4FF",
    iconColor: "#579BFC",
    items: [
      { label: "SEO", icon: "search", href: "#" },
      { label: "AEO", icon: "sparkle", href: "#" },
      { label: "GEO", icon: "robot", href: "#" },
      { label: "Local SEO", icon: "search", href: "#" },
    ],
  },
  {
    label: "AI Marketing",
    subtitle: "Automation & insights",
    avatar: "/avatar/4.avif",
    icon: "sparkle",
    tint: "#FFE8F5",
    iconColor: "#FF5AC4",
    items: [
      { label: "AI-Powered Content Generation", icon: "sparkle", href: "#" },
      { label: "AI Ad Creative & Personalization", icon: "heart", href: "#" },
      { label: "Marketing Automation Agents", icon: "robot", href: "#" },
      { label: "Conversational AI", icon: "headset", href: "#" },
    ],
  },
  {
    label: "Social Media Marketing",
    subtitle: "Content & community",
    avatar: "/avatar/5.avif",
    icon: "megaphone",
    tint: "#E8F8EF",
    iconColor: "#00CA72",
    items: [
      { label: "Social Media Strategy & Management", icon: "megaphone", href: "#" },
      { label: "Community Management", icon: "personPlus", href: "#" },
      { label: "Paid Social Campaigns", icon: "chart", href: "#" },
    ],
  },
  {
    label: "Content Production",
    subtitle: "Videos & storytelling",
    avatar: "/avatar/6.avif",
    icon: "doc",
    tint: "#FFE8E6",
    iconColor: "#E2445C",
    items: [
      { label: "Content Strategy & Editorial Calendars", icon: "doc", href: "#" },
      { label: "Thought Leadership & Whitepapers", icon: "formEdit", href: "#" },
      { label: "Video Production & Editing", icon: "sparkle", href: "#" },
      { label: "Motion Graphics & Animation", icon: "heart", href: "#" },
    ],
  },
  {
    label: "Performance Marketing",
    subtitle: "Ads & conversions",
    avatar: "/avatar/1.avif",
    icon: "chart",
    tint: "#FFF0E6",
    iconColor: "#FDAB3D",
    items: [
      { label: "Paid Search", icon: "search", href: "#" },
      { label: "Paid Social", icon: "megaphone", href: "#" },
      { label: "Landing Page Design & Optimization", icon: "formEdit", href: "#" },
      { label: "Marketing Analytics & ROI Tracking", icon: "chart", href: "#" },
    ],
  },
  {
    label: "Branding & Design",
    subtitle: "Identity & design",
    avatar: "/avatar/2.avif",
    icon: "heart",
    tint: "#F3EEFF",
    iconColor: "#A25DDC",
    items: [
      { label: "Brand Identity & Guidelines", icon: "tag", href: "#" },
      { label: "Brand Strategy & Positioning", icon: "clipboardCheck", href: "#" },
      { label: "UI/UX Design", icon: "gear", href: "#" },
      { label: "Website Design & Development", icon: "doc", href: "#" },
    ],
  },
  {
    label: "Marketing Automation",
    subtitle: "Workflows & CRM",
    avatar: "/avatar/3.avif",
    icon: "robot",
    tint: "#E8F4FF",
    iconColor: "#0086C0",
    items: [
      { label: "Marketing Automation", icon: "robot", href: "#" },
      { label: "CRM Integration", icon: "database", href: "#" },
    ],
  },
];
